name: Auto Release Nudb Client

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP & Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Get Latest Tag and Generate New Version
        id: get_version
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 --match "v[0-9]*.[0-9]*.[0-9]*" 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"

          if [[ $LATEST_TAG =~ v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            PATCH=$(( ${BASH_REMATCH[3]} + 1 ))
            NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          else
            NEW_VERSION="v1.0.0"
          fi

          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create ZIP Archive
        run: |
          zip -r nudb-client-${{ env.new_version }}.zip . \
            -x "*.git*" "tests/*" ".github/*" "*.zip"

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_version }}
          name: "Nudb Client Release ${{ env.new_version }}"
          body: |
            Auto-generated release for Nudb PHP client
            Version: ${{ env.new_version }}
          files: nudb${{ env.new_version }}.zip